MODULE TimeTracking;

REQUIRE Scheduler, Service, SystemEvents, Backup, Eval, SQLUtils, ProcessUtils, Chat, 
        Employee, Customer, Project, Category, ProjectDocument,
        TimeReports, TimeDashboardMobile, 
        InvoiceDashboard, InvoiceWord,
        LegalEntity, 
        EmploymentContract, TimeEntryWord, EGRUL, InvoiceEmail, TaskMonitoringWord, Sale,
        TaskNotification, EnterpriseDataTimeTracking, Currency;
